# Generated by Django 5.1 on 2024-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0003_register_address_register_education_register_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
