# Generated by Django 5.1 on 2024-10-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0011_wishlist_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist_add',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruitapp.product'),
        ),
        migrations.AddField(
            model_name='wishlist_add',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruitapp.register'),
        ),
    ]
