# Generated by Django 5.1 on 2024-10-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0013_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart1',
        ),
    ]
