# Generated by Django 5.1 on 2024-10-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0015_cart1_product_cart1_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart1',
            new_name='add_to_cart',
        ),
    ]
