# Generated by Django 5.1 on 2024-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0016_rename_cart1_add_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
