# Generated by Django 5.1 on 2024-10-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0017_checkout_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_page',
            name='description',
        ),
    ]
