# Generated by Django 5.1 on 2024-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0018_remove_checkout_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_page',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
