# Generated by Django 4.2 on 2024-12-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0024_checkout_page_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout_page',
            old_name='user_id',
            new_name='register',
        ),
    ]
