# Generated by Django 5.1 on 2025-01-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0025_rename_user_id_checkout_page_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitapp.checkout_page')),
                ('product', models.ManyToManyField(to='fruitapp.add_to_cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitapp.register')),
            ],
        ),
    ]
