# Generated by Django 5.1 on 2025-01-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0026_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
