# Generated by Django 5.1 on 2025-01-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0027_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
