# Generated by Django 5.1 on 2025-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0029_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
